---
rg-scheduler:
  channel_name: 'mban2021'
  int_weekday: 7
  int_freq: 1
  str_time: "17:00"
  sec_sleep: 10

rg-participation-scheduler:
  group_size: 4
  int_weekday: 5
  int_freq: 1
  str_time: "9:00"
  sec_sleep: 10